name: 'Upload package from JSON file'
description: "Migration the package defined in the JSON between Organizations"
inputs:
    from-org-pat:
        description: 'Token with read:packages scope for the Organization where the package is stored'
        required: true
    to-org:
        description: 'Name of GitHub Organization where the package should be copied'
        required: true
    to-org-pat:
        description: 'Token with read:packages scope for the Organization where the package should be copied'
        required: true
    package-import-json-file:
        description: 'The JSON file that hold the migration information for the source package'
        required: true
    github-maven-url:
        description: 'The base url of the GitHub Packages Maven repo'
        default: 'https://maven.pkg.github.com'
        required: false
    graphql-query-size:
        description: 'The number of records per page request - reduce if getting timeouts'
        default: '30'
        required: false
    graphql-query-delay:
        description: 'A delay in ms between GraphQL API requests for rate limiting'
        default: '500'
        required: false
outputs:
    results:
        description: 'An object that shows the total results.filesUploaded, results.filesExistAndMatch, and results.filesExistAndNoMatch'

runs:
    using: 'node20'
    main: 'dist/index.mjs'