# This workflow will create a list of all Maven packages for the specified Organization
# 1. The workflow will trigger either by a workflow_dispacth even or by the creation of an issue with the label "get-maven-packages"
# 2. It will use the GitHub CLI to access the GitHub API and get a list of all Maven packages
# 3. It will use the repository secret FROM_ORG_PAT to access the GitHub API

name: Get Maven Packages

on:
    workflow_dispatch:
      inputs:
        org:
          description: 'The organization to get the Maven packages from'
          required: true
          default: 'octodemo'

jobs:
  get-packages:
    runs-on: ubuntu-latest

    outputs:
      packages: ${{ steps.org-packages.outputs.packages }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Get Maven Packages
        uses: ./.github/actions/create-asset-download-lists-by-package
        id: org-packages
        with:
          from-org: ${{ github.event.inputs.org }}
          from-org-pat: ${{ secrets.FROM_ORG_PAT }}

      - name: Add JSON files to cache
        uses: actions/cache@v4.0.1
        with:
          key: |
            ${{ github.workflow }}-${{ github.run_attempt }}-json
          path: |
            *.json
          
      - name: Add list to job summary
        run: |
          echo "Maven Packages" >> $GITHUB_STEP_SUMMARY
          echo "-------------" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.org-packages.outputs.packages }}" >> $GITHUB_STEP_SUMMARY
  
  upload-assets:
    needs: get-packages
    runs-on: ubuntu-latest

    strategy:
        matrix:
          pkg: ${{fromJson(needs.get-packages.outputs.packages)}}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # retrieve cache
      - name: Restore JSON files from cache
        uses: actions/cache@v4.0.1
        with:
          key: |
            ${{ github.workflow }}-${{ github.run_attempt }}-json
          path: |
            *.json 
            
      - name: Read from file ${{ matrix.pkg }}
        run: |
          echo "Reading from file ${{ matrix.pkg }}"
          cat ${{ matrix.pkg }}